@ClassManagement.API_HostAddress = http://localhost:5163
@httpsHost = https://localhost:7233
GET {{ClassManagement.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{httpsHost}}/api/classes/5d14cb6f-c478-491b-997a-b0dacdabf1f5


###

POST {{httpsHost}}/api/classes/
Content-Type: application/json
Accept: application/json
{
  "className": "Literature",
  "startDate": "2024-12-23T09:00:00",
  "endDate": "2025-01-23T09:00:00"
}